"""Verify the remaining `#[cfg(test)]` expectations in subtitle_forge.

`test_subtitle_forge_timecode.py` covers timestamps and
`test_subtitle_forge_wrapping.py` covers the wrapping algorithm itself.  This
file checks the *document-level* expectations: the exact SRT layout, the ASS
structural invariants (23 style columns / 10 dialogue columns), and each
wrapping assertion made by a Rust test case.

Run:  python tests/test_subtitle_forge_render.py
"""

from __future__ import annotations

# Reuse the 1:1 ports from the sibling harnesses.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from test_subtitle_forge_timecode import format_ass_time, format_srt_time  # noqa: E402
from test_subtitle_forge_wrapping import wrap_text  # noqa: E402

# ── renderer ports ───────────────────────────────────────────────────────────

FONT_SIZE_RATIO = 0.05
MARGIN_V_RATIO = 0.10
MARGIN_X_RATIO = 0.0625
OUTLINE_PX = 2.0
SHADOW_PX = 2.0
ALIGNMENT = 2


def scale(base: int, ratio: float) -> int:
    return max(1, round(base * ratio))


def ass_colour(r: int, g: int, b: int, alpha: int) -> str:
    return f"&H{alpha:02X}{b:02X}{g:02X}{r:02X}"


def escape_ass(text: str) -> str:
    out = []
    for ch in text:
        if ch == "{":
            out.append("\\{")
        elif ch == "}":
            out.append("\\}")
        elif ord(ch) < 32 or 0x7F <= ord(ch) <= 0x9F:
            pass
        else:
            out.append(ch)
    return "".join(out)


def render_srt(cues, max_chars=42, max_lines=2) -> str:
    out = []
    for i, (start, end, text) in enumerate(cues):
        if i > 0:
            out.append("\n")
        out.append(str(i + 1))
        out.append("\n")
        out.append(format_srt_time(start))
        out.append(" --> ")
        out.append(format_srt_time(end))
        out.append("\n")
        out.append("\n".join(wrap_text(text, max_chars, max_lines)))
        out.append("\n")
    return "".join(out)


def render_ass(cues, *, play_res_x=1920, play_res_y=1080, font="Roboto",
               font_size=None, margin_l=None, margin_r=None, margin_v=None,
               max_chars=42, max_lines=2, shadow_alpha=128,
               title="T_Dubber") -> str:
    font_size = font_size or scale(play_res_y, FONT_SIZE_RATIO)
    margin_l = margin_l if margin_l is not None else scale(play_res_x, MARGIN_X_RATIO)
    margin_r = margin_r if margin_r is not None else scale(play_res_x, MARGIN_X_RATIO)
    margin_v = margin_v if margin_v is not None else scale(play_res_y, MARGIN_V_RATIO)

    primary = ass_colour(0xFF, 0xFF, 0xFF, 0x00)
    secondary = ass_colour(0xFF, 0xFF, 0xFF, 0x00)
    outline_colour = ass_colour(0x00, 0x00, 0x00, 0x00)
    back_colour = ass_colour(0x00, 0x00, 0x00, shadow_alpha)

    out = ["[Script Info]\n"]
    out.append("; Generated by subtitle_forge 0.1.0\n")
    out.append(f"Title: {title}\n")
    out.append("ScriptType: v4.00+\n")
    out.append("WrapStyle: 0\n")
    out.append("ScaledBorderAndShadow: yes\n")
    out.append("YCbCr Matrix: TV.709\n")
    out.append(f"PlayResX: {play_res_x}\n")
    out.append(f"PlayResY: {play_res_y}\n")
    out.append("Collision: Normal\n\n")

    out.append("[V4+ Styles]\n")
    out.append(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, "
        "ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, "
        "MarginR, MarginV, Encoding\n"
    )
    out.append(
        f"Style: Default,{font},{font_size},{primary},{secondary},"
        f"{outline_colour},{back_colour},0,0,0,0,100,100,0,0,1,"
        f"{OUTLINE_PX:.1f},{SHADOW_PX:.1f},{ALIGNMENT},{margin_l},{margin_r},{margin_v},1\n\n"
    )

    out.append("[Events]\n")
    out.append(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )
    for start, end, text in cues:
        joined = "\\N".join(escape_ass(l) for l in wrap_text(text, max_chars, max_lines))
        out.append(
            f"Dialogue: 0,{format_ass_time(start)},{format_ass_time(end)},"
            f"Default,,0,0,0,,{joined}\n"
        )
    return "".join(out)


def main() -> int:
    failures: list[str] = []
    checks = 0

    def check(cond: bool, msg: str) -> None:
        nonlocal checks
        checks += 1
        if not cond:
            failures.append(msg)

    # ── SRT layout must match mazinger's helper byte for byte ───────────────
    cues = [(0.0, 1.5, "Hello"), (2.0, 3.25, "World")]
    expected = (
        "1\n00:00:00,000 --> 00:00:01,500\nHello\n\n"
        "2\n00:00:02,000 --> 00:00:03,250\nWorld\n"
    )
    check(render_srt(cues) == expected, f"SRT layout:\n{render_srt(cues)!r}")
    check(render_srt([]) == "", "empty SRT must be empty")

    # ── the wrapping assertions made by individual Rust tests ───────────────
    text = "one two three four five six seven eight nine ten eleven twelve"
    lines = wrap_text(text, 20, 10)
    check(len(lines) > 1, f"boundary: expected multiple lines {lines}")
    check(all(len(l) <= 20 for l in lines), f"boundary over budget: {lines}")
    check(all(l == l.strip() for l in lines), f"boundary whitespace: {lines}")
    check(" ".join(lines) == text, f"boundary lost words: {lines}")

    text = "word " + "word " * 39
    text = " ".join(text.split())
    lines = wrap_text(text, 42, 2)
    check(len(lines) == 2, f"widening: expected 2 lines, got {len(lines)}: {lines}")
    check(" ".join(lines) == text, f"widening lost words: {lines}")

    text = "aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa bbbb bbbb bbbb"
    lines = wrap_text(text, 42, 10)
    check(len(lines) > 1, f"char budget: expected multiple lines {lines}")
    check(all(len(l) <= 42 for l in lines), f"char budget over 42: {lines}")
    check(" ".join(lines) == text, f"char budget lost words: {lines}")

    check(
        wrap_text("a very long cue that would otherwise be split", 0, 2)
        == ["a very long cue that would otherwise be split"],
        "max_chars=0",
    )
    check(
        wrap_text("Supercalifragilisticexpialidocious", 10, 2)
        == ["Supercalifragilisticexpialidocious"],
        "oversized word",
    )
    check(wrap_text("   ", 42, 2) == [], "blank text")
    check(wrap_text("short cue", 42, 2) == ["short cue"], "simple fit")

    # ── escaping ────────────────────────────────────────────────────────────
    check(escape_ass("{\\i1}hi") == "\\{\\i1\\}hi", "brace+backslash escape")
    check(escape_ass("a\x07b") == "ab", "control drop")
    check(escape_ass("plain text") == "plain text", "plain passthrough")
    check(ass_colour(0xFF, 0xFF, 0xFF, 0x00) == "&H00FFFFFF", "white")
    check(ass_colour(0x00, 0x00, 0x00, 128) == "&H80000000", "shadow black 50%")

    # ── ASS structural invariants ───────────────────────────────────────────
    ass_cues = [(0.0, 1.5, "Hello"), (1.0, 2.5, "Overlap")]
    out = render_ass(ass_cues)

    fmt_line = next(l for l in out.splitlines() if l.startswith("Format: Name,"))
    style_line = next(l for l in out.splitlines() if l.startswith("Style: "))
    n_fmt = len(fmt_line[len("Format: "):].split(","))
    n_style = len(style_line[len("Style: "):].split(","))
    check(n_fmt == 23, f"expected 23 format columns, got {n_fmt}")
    check(n_fmt == n_style, f"Style/Format mismatch: {n_style} vs {n_fmt}")

    dlg = [l for l in out.splitlines() if l.startswith("Dialogue: ")]
    check(len(dlg) == 2, f"expected 2 dialogues, got {len(dlg)}")
    for line in dlg:
        body = line[len("Dialogue: "):]
        check(len(body.split(",")) >= 10, f"dialogue has <10 fields: {line}")

    for header in ("[Script Info]", "[V4+ Styles]", "[Events]"):
        check(header in out, f"missing {header}")
    check("&H80000000" in out, "missing 50% shadow")
    check(f"PlayResX: 1920" in out and f"PlayResY: 1080" in out, "playres")

    # defaults, 1080p
    check(scale(1080, FONT_SIZE_RATIO) == 54, "font size default")
    check(scale(1080, MARGIN_V_RATIO) == 108, "margin V default")
    check(scale(1920, MARGIN_X_RATIO) == 120, "margin L default")
    # defaults, 720p
    check(scale(720, FONT_SIZE_RATIO) == 36, "font size 720p")
    check(scale(720, MARGIN_V_RATIO) == 72, "margin V 720p")
    check(scale(1280, MARGIN_X_RATIO) == 80, "margin L 720p")

    # ── ASS hard-break cue ──────────────────────────────────────────────────
    multi = [(0.0, 1.0, "first half second half third half fourth")]
    out = render_ass(multi, max_chars=20, max_lines=2)
    dlg = next(l for l in out.splitlines() if l.startswith("Dialogue: "))
    check("\\N" in dlg, f"expected hard break: {dlg}")

    # ── braces must never leak as an override block ─────────────────────────
    out = render_ass([(0.0, 1.0, "a {b} c")])
    dlg = next(l for l in out.splitlines() if l.startswith("Dialogue: "))
    check("\\{b\\}" in dlg, f"brace not escaped: {dlg}")
    check(",{b}," not in dlg, f"raw braces leaked: {dlg}")

    if failures:
        print(f"FAIL ({len(failures)} of {checks} checks)")
        for line in failures:
            print("  -", line)
        return 1
    print(f"PASS ({checks} checks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
